#!/bin/sh

if [ ! -e src ]; then echo "Not in source directory"; exit 1; fi
if [ -e output ]; then rm -r output; fi
if [ -e '/tmp/eartag' ]; then rm -r '/tmp/eartag'; fi

set -e
meson setup --prefix=/tmp/eartag -Ddevel=true . output
meson compile -C output
meson install -C output
set +e

GSETTINGS_SCHEMA_DIR=/tmp/eartag/share/glib-2.0/schemas /tmp/eartag/bin/eartag-devel "$@"
ret=$?

exit $ret
