#!/bin/sh

if [ ! -e src ]; then echo "Not in source directory"; exit 1; fi
if [ -e output ]; then rm -r output; fi
if [ -e '/tmp/eartag' ]; then rm -r '/tmp/eartag'; fi

set -e
meson setup --prefix=/tmp/eartag -Denable_networked_tests=true . output
meson compile -C output
meson test -v -C output
ret=$?
set +e

exit $ret
